2024-11-27 11:20:50,089 (30427/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-27 11:21:10,109 (30427/MainThread) pgcli.pgexecute ERROR - sql: 'create database askmerlin-27-11-2024', error: SyntaxError('syntax error at or near "-"\nLINE 1: create database askmerlin-27-11-2024\n                                 ^')
2024-11-27 11:21:10,112 (30427/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/nix/store/maav2q50g74hcv8pjrfq79a9q8r6y42q-python3.12-psycopg-3.2.1/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "-"\nLINE 1: create database askmerlin-27-11-2024\n                                 ^\n'
2024-11-27 15:46:01,925 (50527/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-28 10:35:52,988 (16006/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-28 10:35:53,168 (16006/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/maav2q50g74hcv8pjrfq79a9q8r6y42q-python3.12-psycopg-3.2.1/lib/python3.12/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/var/folders/cq/2t2_83rx7v96qnwv9f27thpm0000gp/T/devenv-bf7ce91/postgres/.s.PGSQL.5433" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-11-28 10:37:44,519 (36146/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-28 10:37:44,650 (36146/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/maav2q50g74hcv8pjrfq79a9q8r6y42q-python3.12-psycopg-3.2.1/lib/python3.12/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server on socket "/var/folders/cq/2t2_83rx7v96qnwv9f27thpm0000gp/T/devenv-bf7ce91/postgres/.s.PGSQL.5433" failed: FATAL:  database "harvey" does not exist\n'
2024-11-28 10:37:49,362 (37044/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-28 10:38:33,902 (45123/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-29 09:45:48,686 (51499/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-29 09:46:08,645 (51499/MainThread) pgcli.pgexecute ERROR - sql: 'create database askmerlin_29_11_2024_2', error: DuplicateDatabase('database "askmerlin_29_11_2024_2" already exists')
2024-11-29 09:46:08,648 (51499/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/nix/store/maav2q50g74hcv8pjrfq79a9q8r6y42q-python3.12-psycopg-3.2.1/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.DuplicateDatabase: database "askmerlin_29_11_2024_2" already exists\n'
2024-12-02 14:48:35,950 (47904/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-02 14:48:46,873 (47904/MainThread) pgcli.pgexecute ERROR - sql: 'create database askmerlin_02_12_2024_1', error: DuplicateDatabase('database "askmerlin_02_12_2024_1" already exists')
2024-12-02 14:48:46,878 (47904/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/nix/store/maav2q50g74hcv8pjrfq79a9q8r6y42q-python3.12-psycopg-3.2.1/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.DuplicateDatabase: database "askmerlin_02_12_2024_1" already exists\n'
2024-12-05 16:55:19,706 (55043/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-06 11:13:16,891 (11290/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-08 21:42:30,837 (36640/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-08 21:42:35,857 (36640/MainThread) pgcli.pgexecute ERROR - sql: 'show database', error: UndefinedObject('unrecognized configuration parameter "database"')
2024-12-08 21:42:35,861 (36640/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/nix/store/maav2q50g74hcv8pjrfq79a9q8r6y42q-python3.12-psycopg-3.2.1/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedObject: unrecognized configuration parameter "database"\n'
2024-12-08 21:42:39,546 (36640/MainThread) pgcli.pgexecute ERROR - sql: 'databases', error: SyntaxError('syntax error at or near "databases"\nLINE 1: databases\n        ^')
2024-12-08 21:42:39,547 (36640/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/nix/store/maav2q50g74hcv8pjrfq79a9q8r6y42q-python3.12-psycopg-3.2.1/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "databases"\nLINE 1: databases\n        ^\n'
2024-12-09 10:10:26,998 (70991/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-09 11:07:00,313 (70991/MainThread) pgcli.pgexecute ERROR - sql: '!!!', error: SyntaxError('syntax error at or near "!!!"\nLINE 1: !!!\n        ^')
2024-12-09 11:07:00,325 (70991/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/nix/store/maav2q50g74hcv8pjrfq79a9q8r6y42q-python3.12-psycopg-3.2.1/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "!!!"\nLINE 1: !!!\n        ^\n'
2024-12-10 13:41:03,292 (22077/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-10 13:41:03,407 (22077/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/maav2q50g74hcv8pjrfq79a9q8r6y42q-python3.12-psycopg-3.2.1/lib/python3.12/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/var/folders/cq/2t2_83rx7v96qnwv9f27thpm0000gp/T/devenv-bf7ce91/postgres/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-12-11 11:02:32,207 (70554/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-12 11:22:56,344 (99767/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-12 11:57:25,987 (28808/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-12 11:59:14,798 (35202/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-16 12:10:47,422 (42249/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-16 12:11:28,116 (58582/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-16 13:18:55,222 (46717/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-16 13:18:55,348 (46717/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/nix/store/jfrjq29iiv13q3wbljkn3zlqcnb90rf4-python3.12-pgcli-4.1.0/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/maav2q50g74hcv8pjrfq79a9q8r6y42q-python3.12-psycopg-3.2.1/lib/python3.12/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server on socket "/var/folders/cq/2t2_83rx7v96qnwv9f27thpm0000gp/T/devenv-bf7ce91/postgres/.s.PGSQL.5432" failed: FATAL:  database "harvey" does not exist\n'
2024-12-16 13:19:00,232 (53938/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-17 14:34:20,321 (85532/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-18 10:45:07,081 (24457/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
